# Generated by Django 4.2.6 on 2023-12-17 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_authuser_options_alter_labs_cabinets_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labs_cabinets',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.office', verbose_name='Кабинет сис. Админа'),
        ),
    ]
